export default {
  invalidFirstName: {
    first_name: "Jamal*",
    last_name: "Kadhuwa",
    username: "Kaduzi",
    email: "jamal@gmail.com",
    password: "Jamal123",
    confirm_password: "Jamal123",
  },
  firstNumFirst_name: {
    first_name: "1Jamal",
    last_name: "Kadhuwa",
    username: "Kaduzi",
    email: "jamal@gmail.com",
    password: "Jamal123",
    confirm_password: "Jamal123",
  },
  numFirstName: {
    first_name: 1,
    last_name: "Kadhuwa",
    username: "Kaduzi",
    email: "jamal@gmail.com",
    password: "Jamal123",
    confirmPassword: "Jamal123",
  },
  lessFirstName: {
    first_name: "J",
    last_name: "Kadhuwa",
    username: "Kaduzi",
    email: "jamal@gmail.com",
    password: "Jamal123",
    confirmPassword: "Jamal123",
  },
  missingFirstName: {
    last_name: "Kadhuwa",
    username: "Kaduzi",
    email: "jamal@gmail.com",
    password: "Jamal123",
    confirm_password: "Jamal123",
  },
  invalidLastName: {
    first_name: "Jamal",
    last_name: "Kadhuwa*",
    username: "Kaduzi",
    email: "jamal@gmail.com",
    password: "Jamal123",
    confirmPassword: "Jamal123",
  },
  firstNumLastName: {
    first_name: "Jamal",
    last_name: "2Kadhuwa",
    username: "Kaduzi",
    email: "jamal@gmail.com",
    password: "Jamal.123",
    confirmPassword: "Jamal.123",
  },
  missingLastName: {
    first_name: "Jamal",
    username: "Kaduzi",
    email: "jamal@gmail.com",
    password: "Jamal123",
    confirm_password: "Jamal123",
  },
  lessLastName: {
    first_name: "Jamal",
    last_name: "K",
    username: "Kaduzi",
    email: "jamal@gmail.com",
    password: "Jamal123",
    confirmPassword: "Jamal123",
  },
  numLastName: {
    first_name: "jamal",
    last_name: 2,
    username: "Kaduzi",
    email: "jamal@gmail.com",
    password: "Jamal123",
    confirm_password: "Jamal123",
  },
  invalidUserName: {
    first_name: "Jamal",
    last_name: "Kadhuwa",
    username: "Kad*",
    email: "jamal@gmail.com",
    password: "Jamal123",
    confirm_password: "Jamal123",
  },
  missingUserName: {
    first_name: "Jamal",
    last_name: "Kadhuwa",
    email: "jamal@gmail.com",
    password: "Jamal123",
    confirm_password: "Jamal123",
  },
  firstNumUserName: {
    first_name: "Jamal",
    last_name: "Kadhuwa",
    username: "3Kaduzi",
    email: "jamal@gmail.com",
    password: "Jamal123",
    confirmPassword: "Jamal123",
  },
  numUserName: {
    first_name: "jamal",
    last_name: "Kadhua",
    username: 3,
    email: "jamal@gmail.com",
    password: "Jamal123",
    confirmPassword: "Jamal123",
  },
  lessUserName: {
    first_name: "Jamal",
    last_name: "Kadhua",
    username: "K",
    email: "jamal@gmail.com",
    password: "Jamal123",
    confirm_password: "Jamal123",
  },
  invalidEmail: {
    first_name: "Jamal",
    last_name: "Kadhuwa",
    username: "Kadhu",
    email: "jamalgmail.com",
    password: "Jamal123",
    confirm_password: "Jamal123",
  },
  missingEmail: {
    first_name: "Jamal",
    last_name: "Kadhuwa",
    username: "Kadhu",
    password: "Jamal123",
    confirm_password: "Jamal123",
  },
  invalidPassword: {
    first_name: "Jamal",
    last_name: "Kadhuwa",
    username: "Kadhu",
    email: "jamal@gmail.com",
    password: "Jamal",
    confirm_password: "Jamal123",
  },
  missingPassword: {
    first_name: "Jamal",
    last_name: "Kadhuwa",
    username: "Kadhu",
    email: "jamal@gmail.com",
  },
  unmatchedPassword: {
    first_name: "Jamal",
    last_name: "Kadhuwa",
    username: "Kadhu",
    email: "jamal@gmail.com",
    password: "Jama.l123",
    confirm_password: "Jamal12",
  },
  existingEmail: {
    first_name: "Jamal",
    last_name: "Kadhuwa",
    username: "Kadhut",
    email: "raymond42.gr@gmail.com",
    password: "Jamal.123",
    confirm_password: "Jamal.123",
  },
  existingUserName: {
    first_name: "Jamal",
    last_name: "Kadhuwa",
    username: "Kadhut",
    email: "kad@gmail.com",
    password: "Jamal.123",
    confirm_password: "Jamal.123",
  },
  missingConfirm: {
    first_name: "Jamal",
    last_name: "Kadhuwa",
    username: "Kaduzi",
    email: "jamal@gmail.com",
    password: "Jamal.123",
  },
  numConfirmPassword: {
    first_name: "Jamal",
    last_name: "Kadhuwa",
    username: "Kaduzi",
    email: "jamal@gmail.com",
    password: "Jamal.123",
    confirm_password: 1,
  },
  validUser: {
    first_name: "Jamal",
    last_name: "Kadhuwa",
    username: "Kadhut",
    email: "raymond42.gr@gmail.com",
    password: "Jamal.123",
    confirm_password: "Jamal.123",
  },
  emailForSend: {
    email: "raymond42.gr@gmail.com",
  },
};
